### ISSUE TITLE
'assert' was not declared in this scope

### ISSUE THREAD

**Issue by varungujjar** [malokhvii-eduard/arduino-mhz19#1]
Hi, 

Every time I try to compile it gives me the following error 

.pio/libdeps/esp12e/arduino-mhz19/src/Mhz19.cc: In member function 'int Mhz19::getCarbonDioxide() const':
.pio/libdeps/esp12e/arduino-mhz19/src/Mhz19.cc:36:28: error: 'assert' was not declared in this scope
   assert(serial_ != nullptr);
                            ^
.pio/libdeps/esp12e/arduino-mhz19/src/Mhz19.cc: In member function 'bool Mhz19::sendCommand(const uint8_t*) const':
.pio/libdeps/esp12e/arduino-mhz19/src/Mhz19.cc:114:28: error: 'assert' was not declared in this scope
   assert(serial_ != nullptr);

**Comment by malokhvii-eduard** [comment]
Hi, thank you @varungujjar for raising the issue. I'll resolve the problem as soon as possible, or you can contribute to the library.

**Comment by malokhvii-eduard** [comment]
@varungujjar on which board did you get the issue?
