### ISSUE TITLE
Device never ready

### ISSUE THREAD

**Issue by adimux** [malokhvii-eduard/arduino-mhz19#3]
Hi first of all thanks for providing this library!
I have a ESP32 module connected to MH-Z19C like so:
| MH-Z19C |  ESP32         |
|------------|---------------|
|     VIN      |     3V3        |
|     GND    |     GND       |
|     RX        |    TX2 (17)  |
|     TX        |    RX2 (16)  |

As seen in the schematics of [ESP32](https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2018/08/ESP32-DOIT-DEVKIT-V1-Board-Pinout-36-GPIOs-updated.jpg?quality=100&strip=all&ssl=1) RX2 is PIN 16 and TX 2 is PIN 17.

I took your basic example but the device never seems to be "ready".
I also tried to remove the "ready" condition to see if it's able to get any reading but it's always `- 1 ppm`.

What did I do wrong?
How can I debug this?
Thank you!

```#include <Arduino.h>
#include <Mhz19.h>
#include <SoftwareSerial.h>

SoftwareSerial softwareSerial(16, 17); 

Mhz19 sensor;

void setup() {
  Serial.begin(9600);
  softwareSerial.begin(9600);

  sensor.begin(&softwareSerial);
  sensor.setMeasuringRange(Mhz19MeasuringRange::Ppm_2000);
  sensor.enableAutoBaseCalibration();

  Serial.println("Preheating...");  // Preheating, 3 minutes
  while (!sensor.isReady()) {
    delay(50);
    Serial.println("Preheating...");
  }

  Serial.println("Ready...");
}

void loop() {
  auto carbonDioxide = sensor.getCarbonDioxide();
  Serial.println(String(carbonDioxide) + " ppm");
  if (carbonDioxide >= 0) {
    Serial.println(String(carbonDioxide) + " ppm");
  }

  delay(3000);
}
```

**Comment by malokhvii-eduard** [comment]
@adimux Hi! Thanks for the issue and sorry for the long reply. You have the wrong pins in the firmware. Can you swap the _RX_ and _TX_ pins only in the code? So it has to be `SoftwareSerial softwareSerial(17, 16);`. Please, let me know if it helps you.

**Comment by malokhvii-eduard** [comment]
@adimux Can you try the example code with a hardware serial?

**Comment by malokhvii-eduard** [comment]
@adimux Please try to use macros for pin mappings. Here's a [header with pin mappings](https://github.com/espressif/arduino-esp32/blob/master/variants/feather_esp32/pins_arduino.h).
